# NumPy

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

In [2]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [3]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [4]:
# we can create numpy arrays by converting lists
# this is a vector
vec = np.array([1,2,3])
print(vec)
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T)

[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [5]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0,15)
print(vec2)
print('')
vec3 = np.arange(3,21,6)
print(vec3)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [6]:

vec4 = np.linspace(0,5,10)
print(vec4)
print('')
print(vec4.reshape(5,2))
vec4_reshaped = vec4.reshape(5,2)
print(vec4_reshaped)
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [7]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,5))
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [8]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [9]:
# we can do matrix multiplication
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[ 8 41 44]


In [10]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

[1. 2. 3.]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [11]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [12]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.13395635 0.43780918 0.21583656 0.66779452 0.63893444]
 [0.76713151 0.98186134 0.52624881 0.39635048 0.15720595]
 [0.33413073 0.68001501 0.91788353 0.67605453 0.98339954]
 [0.27573719 0.94578309 0.18105865 0.2611447  0.67534503]
 [0.45032673 0.71877521 0.70479285 0.32400051 0.77337593]]

[[ 0.43902515 -0.46688111  0.85298462  2.24570382 -0.28799907]
 [-1.59395062  0.43355401  0.5371613   0.27235541 -0.16997902]
 [-0.44374495 -1.05093865  0.32488959 -0.60380936  0.11528604]
 [-0.05783153 -1.86279386  2.23282424 -0.88718963  0.81747165]
 [-0.63722471  0.28165694 -0.3606894   1.83191642  1.43592992]
 [-1.67631876 -0.72360222 -0.41104216 -0.45850662 -1.1223591 ]
 [-0.66491448 -0.68318902 -0.94066356  0.47538348  0.53695773]
 [-1.18991537  0.0614109  -0.16686909 -1.25715181 -0.52331835]
 [ 0.66524492  0.21416977 -0.87954927 -1.05288396 -0.4373041 ]
 [-0.16628357  1.7012097  -0.37944256  0.55698344 -1.65890692]]


In [13]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.5529980946756531
0.9536132638919038


In [14]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.13395635238426573
2.245703820666249


In [15]:
# break here for next video!

In [16]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[-1.17530797 -0.3118973   1.52595324  2.10073436  0.59386604  0.36775905
  0.72235708  0.16873629 -1.78871885  0.33289177 -0.21882164  0.02553161
  0.74551325 -0.27812266 -0.10442011 -1.15666198 -0.29657798 -0.2063654
 -0.39673768]
0.7223570803312296


In [17]:
# we can access multiple entries at once using :
print(rand_vec[4:9])

[ 0.59386604  0.36775905  0.72235708  0.16873629 -1.78871885]


In [18]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[-1.17530797  2.10073436  0.72235708  0.33289177  0.74551325]


In [19]:
# what about matrices
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])


[[0.13395635 0.43780918 0.21583656 0.66779452 0.63893444]
 [0.76713151 0.98186134 0.52624881 0.39635048 0.15720595]
 [0.33413073 0.68001501 0.91788353 0.67605453 0.98339954]
 [0.27573719 0.94578309 0.18105865 0.2611447  0.67534503]
 [0.45032673 0.71877521 0.70479285 0.32400051 0.77337593]]
0.5262488119165738
0.5262488119165738


In [20]:
print(rand_mat[0:2,1:3])

[[0.43780918 0.21583656]
 [0.98186134 0.52624881]]


In [21]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[-1.17530797 -0.3118973   1.52595324  2.10073436  0.59386604  0.36775905
  0.72235708  0.16873629 -1.78871885  0.33289177 -0.21882164  0.02553161
  0.74551325 -0.27812266 -0.10442011 -1.15666198 -0.29657798 -0.2063654
 -0.39673768]

[-1.17530797 -0.3118973   1.52595324  4.          4.          0.36775905
  0.72235708  0.16873629 -1.78871885  0.33289177 -0.21882164  0.02553161
  0.74551325 -0.27812266 -0.10442011 -1.15666198 -0.29657798 -0.2063654
 -0.39673768]

[-1.17530797 -0.3118973   1.52595324  1.          2.          0.36775905
  0.72235708  0.16873629 -1.78871885  0.33289177 -0.21882164  0.02553161
  0.74551325 -0.27812266 -0.10442011 -1.15666198 -0.29657798 -0.2063654
 -0.39673768]


In [22]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[0.13395635 0.43780918 0.21583656 0.66779452 0.63893444]
 [0.76713151 0.98186134 0.52624881 0.39635048 0.15720595]
 [0.33413073 0.68001501 0.91788353 0.67605453 0.98339954]
 [0.27573719 0.94578309 0.18105865 0.2611447  0.67534503]
 [0.45032673 0.71877521 0.70479285 0.32400051 0.77337593]]

[[0.13395635 0.43780918 0.21583656 0.66779452 0.63893444]
 [0.76713151 0.98186134 0.52624881 0.         0.        ]
 [0.33413073 0.68001501 0.91788353 0.         0.        ]
 [0.27573719 0.94578309 0.18105865 0.2611447  0.67534503]
 [0.45032673 0.71877521 0.70479285 0.32400051 0.77337593]]


In [23]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)


[[0.13395635 0.43780918 0.21583656]
 [0.76713151 0.98186134 0.52624881]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [24]:
print(rand_mat)

[[3.         3.         3.         0.66779452 0.63893444]
 [3.         3.         3.         0.         0.        ]
 [0.33413073 0.68001501 0.91788353 0.         0.        ]
 [0.27573719 0.94578309 0.18105865 0.2611447  0.67534503]
 [0.45032673 0.71877521 0.70479285 0.32400051 0.77337593]]


In [25]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)


[[99. 99. 99.]
 [99. 99. 99.]]
[[3.         3.         3.         0.66779452 0.63893444]
 [3.         3.         3.         0.         0.        ]
 [0.33413073 0.68001501 0.91788353 0.         0.        ]
 [0.27573719 0.94578309 0.18105865 0.2611447  0.67534503]
 [0.45032673 0.71877521 0.70479285 0.32400051 0.77337593]]


In [26]:
# break here for next video

In [27]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)

print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[ 0.6965522  -0.80037279  2.23069024  2.16407025 -2.20029878 -0.04459028
 -0.23399231 -0.71597312  0.11148749  0.32661519  0.82681699 -0.55685075
  1.06136989 -0.65450539 -0.54584459]
[ True False  True  True False False False False  True  True  True False
  True False False]
[0.6965522  2.23069024 2.16407025 0.11148749 0.32661519 0.82681699
 1.06136989]


In [28]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[ 0.43902515 -0.46688111  0.85298462  2.24570382 -0.28799907]
 [-1.59395062  0.43355401  0.5371613   0.27235541 -0.16997902]
 [-0.44374495 -1.05093865  0.32488959 -0.60380936  0.11528604]
 [-0.05783153 -1.86279386  2.23282424 -0.88718963  0.81747165]
 [-0.63722471  0.28165694 -0.3606894   1.83191642  1.43592992]
 [-1.67631876 -0.72360222 -0.41104216 -0.45850662 -1.1223591 ]
 [-0.66491448 -0.68318902 -0.94066356  0.47538348  0.53695773]
 [-1.18991537  0.0614109  -0.16686909 -1.25715181 -0.52331835]
 [ 0.66524492  0.21416977 -0.87954927 -1.05288396 -0.4373041 ]
 [-0.16628357  1.7012097  -0.37944256  0.55698344 -1.65890692]]
[0.43902515 0.85298462 2.24570382 0.43355401 0.5371613  0.27235541
 0.32488959 0.11528604 2.23282424 0.81747165 0.28165694 1.83191642
 1.43592992 0.47538348 0.53695773 0.0614109  0.66524492 0.21416977
 1.7012097  0.55698344]


In [29]:

print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

[ 0.6965522  -0.80037279  2.23069024  2.16407025 -2.20029878 -0.04459028
 -0.23399231 -0.71597312  0.11148749  0.32661519  0.82681699 -0.55685075
  1.06136989 -0.65450539 -0.54584459]

[-5.         -0.80037279 -5.         -5.         -2.20029878 -0.04459028
 -0.23399231 -0.71597312  0.11148749  0.32661519 -5.         -0.55685075
 -5.         -0.65450539 -0.54584459]


In [30]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)


In [31]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [32]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

[[ 0.43902515 -0.46688111  0.85298462  2.24570382 -0.28799907]
 [-1.59395062  0.43355401  0.5371613   0.27235541 -0.16997902]
 [-0.44374495 -1.05093865  0.32488959 -0.60380936  0.11528604]
 [-0.05783153 -1.86279386  2.23282424 -0.88718963  0.81747165]
 [-0.63722471  0.28165694 -0.3606894   1.83191642  1.43592992]
 [-1.67631876 -0.72360222 -0.41104216 -0.45850662 -1.1223591 ]
 [-0.66491448 -0.68318902 -0.94066356  0.47538348  0.53695773]
 [-1.18991537  0.0614109  -0.16686909 -1.25715181 -0.52331835]
 [ 0.66524492  0.21416977 -0.87954927 -1.05288396 -0.4373041 ]
 [-0.16628357  1.7012097  -0.37944256  0.55698344 -1.65890692]]



In [33]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array  = loaded_zip['rand_mat']
print(new_array)

[[3.         3.         3.         0.66779452 0.63893444]
 [3.         3.         3.         0.         0.        ]
 [0.33413073 0.68001501 0.91788353 0.         0.        ]
 [0.27573719 0.94578309 0.18105865 0.2611447  0.67534503]
 [0.45032673 0.71877521 0.70479285 0.32400051 0.77337593]]

[[ 0.43902515 -0.46688111  0.85298462  2.24570382 -0.28799907]
 [-1.59395062  0.43355401  0.5371613   0.27235541 -0.16997902]
 [-0.44374495 -1.05093865  0.32488959 -0.60380936  0.11528604]
 [-0.05783153 -1.86279386  2.23282424 -0.88718963  0.81747165]
 [-0.63722471  0.28165694 -0.3606894   1.83191642  1.43592992]
 [-1.67631876 -0.72360222 -0.41104216 -0.45850662 -1.1223591 ]
 [-0.66491448 -0.68318902 -0.94066356  0.47538348  0.53695773]
 [-1.18991537  0.0614109  -0.16686909 -1.25715181 -0.52331835]
 [ 0.66524492  0.21416977 -0.87954927 -1.05288396 -0.4373041 ]
 [-0.16628357  1.7012097  -0.37944256  0.55698344 -1.65890692]]
[[3.         3.         3.         0.66779452 0.63893444]
 [3.         3.    

In [34]:
# we can also save/load as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)

[[3.         3.         3.         0.66779452 0.63893444]
 [3.         3.         3.         0.         0.        ]
 [0.33413073 0.68001501 0.91788353 0.         0.        ]
 [0.27573719 0.94578309 0.18105865 0.2611447  0.67534503]
 [0.45032673 0.71877521 0.70479285 0.32400051 0.77337593]]

[[3.         3.         3.         0.66779452 0.63893444]
 [3.         3.         3.         0.         0.        ]
 [0.33413073 0.68001501 0.91788353 0.         0.        ]
 [0.27573719 0.94578309 0.18105865 0.2611447  0.67534503]
 [0.45032673 0.71877521 0.70479285 0.32400051 0.77337593]]
